/**
 * GRADE 4 BANK — 15 items, 5 minutes.
 *
 * ===========================================================================
 * THIS IS SCAFFOLDING. THE CONTENT IS NOT FINAL.
 * ===========================================================================
 * Generated by scripts/generate-tests.mjs. Every item carries
 * `placeholder: true`. The figure matrices and number analogies are genuine
 * puzzles derived from docs/test-content/rule-taxonomy.md; the verbal analogies
 * are plainly filler. Difficulty is UNCALIBRATED for this grade.
 *
 * ===========================================================================
 * THE STRUCTURE, WHICH IS REAL
 * ===========================================================================
 * Fifteen items in five minutes, about twenty seconds each: 5 verbal analogies,
 * 5 number analogies, 5 figure matrices, interleaved.
 *
 * That is not an arbitrary truncation. The publisher of the instrument this
 * mirrors sells an official Screening Form that keeps ONLY the analogies
 * subtest from each of the three batteries — their own answer to "what is the
 * minimum viable version of this". Following that logic gives the short test a
 * rationale instead of a guess.
 *
 * NO LETTER SERIES: the child quantitative battery uses number series, not
 * letters. Paper folding is available to child tests but is not part of the
 * fifteen-item screening structure, so it belongs here only if this bank grows.
 *
 * TO LAND REAL CONTENT: edit this file. It is plain data, nothing regenerates
 * it at build time. Delete the `placeholder` flags as you go and run
 * `npm run verify:tests`.
 */
import type { Test } from "../types";

export const GRADE_4_TEST: Test = {
  id: "grade-4",
  audience: "child",
  bank: "grade-4",
  grades: [4],
  band: "grade-4",
  title: "The 5-Minute Grade 4 Test",
  durationSeconds: 5 * 60,
  allowBack: true,
  placeholder: true,
  items: [
    {
      id: "grade-4-01",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "D",
    },
    {
      id: "grade-4-02",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "2 is to 6 as 8 is to ?",
      options: [
        { id: "A", text: "24" },
        { id: "B", text: "12" },
        { id: "C", text: "16" },
        { id: "D", text: "32" },
      ],
      explanation: "The rule is multiply by 3, so 8 becomes 24.",
      answer: "A",
    },
    {
      id: "grade-4-03",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        { shapes: [{ shape: "square" }] },
        { shapes: [{ shape: "square", filled: true }] },
        { shapes: [{ shape: "star" }] },
      ],
      options: [
        { id: "A", fig: { shapes: [{ shape: "star" }] } },
        { id: "B", fig: { shapes: [{ shape: "square", filled: true }] } },
        { id: "C", fig: { shapes: [{ shape: "cross", filled: true }] } },
        { id: "D", fig: { shapes: [{ shape: "star", filled: true }] } },
      ],
      explanation: "The shape stays the same and fills in.",
      answer: "D",
    },
    {
      id: "grade-4-04",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "C",
    },
    {
      id: "grade-4-05",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "5 is to 30 as 6 is to ?",
      options: [
        { id: "A", text: "42" },
        { id: "B", text: "36" },
        { id: "C", text: "31" },
        { id: "D", text: "30" },
      ],
      explanation: "The rule is multiply by 6, so 6 becomes 36.",
      answer: "B",
    },
    {
      id: "grade-4-06",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/count-doubles",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        { shapes: [{ shape: "star", filled: true }] },
        {
          shapes: [{ shape: "star", filled: true }, { shape: "star", filled: true }],
        },
        { shapes: [{ shape: "arrow", filled: true }] },
      ],
      options: [
        {
          id: "A",
          fig: {
            shapes: [{ shape: "arrow", filled: true }, { shape: "arrow", filled: true }],
          },
        },
        { id: "B", fig: { shapes: [{ shape: "arrow", filled: true }] } },
        {
          id: "C",
          fig: {
            shapes: [
              { shape: "arrow", filled: true },
              { shape: "arrow", filled: true },
              { shape: "arrow", filled: true },
            ],
          },
        },
        {
          id: "D",
          fig: {
            shapes: [{ shape: "star", filled: true }, { shape: "star", filled: true }],
          },
        },
      ],
      explanation: "The count doubles across the row while the shape stays the same.",
      answer: "A",
    },
    {
      id: "grade-4-07",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "B",
    },
    {
      id: "grade-4-08",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "4 is to 20 as 9 is to ?",
      options: [
        { id: "A", text: "36" },
        { id: "B", text: "54" },
        { id: "C", text: "45" },
        { id: "D", text: "25" },
      ],
      explanation: "The rule is multiply by 5, so 9 becomes 45.",
      answer: "C",
    },
    {
      id: "grade-4-09",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        { shapes: [{ shape: "arrow" }] },
        { shapes: [{ shape: "arrow", filled: true }] },
        { shapes: [{ shape: "triangle" }] },
      ],
      options: [
        { id: "A", fig: { shapes: [{ shape: "star", filled: true }] } },
        { id: "B", fig: { shapes: [{ shape: "triangle", filled: true }] } },
        { id: "C", fig: { shapes: [{ shape: "triangle" }] } },
        { id: "D", fig: { shapes: [{ shape: "arrow", filled: true }] } },
      ],
      explanation: "The shape stays the same and fills in.",
      answer: "B",
    },
    {
      id: "grade-4-10",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "A",
    },
    {
      id: "grade-4-11",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "3 is to 12 as 7 is to ?",
      options: [
        { id: "A", text: "16" },
        { id: "B", text: "21" },
        { id: "C", text: "35" },
        { id: "D", text: "28" },
      ],
      explanation: "The rule is multiply by 4, so 7 becomes 28.",
      answer: "D",
    },
    {
      id: "grade-4-12",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/count-doubles",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        { shapes: [{ shape: "triangle", filled: true }] },
        {
          shapes: [
            { shape: "triangle", filled: true },
            { shape: "triangle", filled: true },
          ],
        },
        { shapes: [{ shape: "heart", filled: true }] },
      ],
      options: [
        {
          id: "A",
          fig: {
            shapes: [
              { shape: "heart", filled: true },
              { shape: "heart", filled: true },
              { shape: "heart", filled: true },
            ],
          },
        },
        {
          id: "B",
          fig: {
            shapes: [
              { shape: "triangle", filled: true },
              { shape: "triangle", filled: true },
            ],
          },
        },
        {
          id: "C",
          fig: {
            shapes: [{ shape: "heart", filled: true }, { shape: "heart", filled: true }],
          },
        },
        { id: "D", fig: { shapes: [{ shape: "heart", filled: true }] } },
      ],
      explanation: "The count doubles across the row while the shape stays the same.",
      answer: "C",
    },
    {
      id: "grade-4-13",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "D",
    },
    {
      id: "grade-4-14",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "2 is to 6 as 5 is to ?",
      options: [
        { id: "A", text: "15" },
        { id: "B", text: "9" },
        { id: "C", text: "10" },
        { id: "D", text: "20" },
      ],
      explanation: "The rule is multiply by 3, so 5 becomes 15.",
      answer: "A",
    },
    {
      id: "grade-4-15",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        { shapes: [{ shape: "heart" }] },
        { shapes: [{ shape: "heart", filled: true }] },
        { shapes: [{ shape: "circle" }] },
      ],
      options: [
        { id: "A", fig: { shapes: [{ shape: "circle" }] } },
        { id: "B", fig: { shapes: [{ shape: "heart", filled: true }] } },
        { id: "C", fig: { shapes: [{ shape: "triangle", filled: true }] } },
        { id: "D", fig: { shapes: [{ shape: "circle", filled: true }] } },
      ],
      explanation: "The shape stays the same and fills in.",
      answer: "D",
    },
  ],
};
