/**
 * GRADE 6 BANK — 15 items, 5 minutes.
 *
 * ===========================================================================
 * THIS IS SCAFFOLDING. THE CONTENT IS NOT FINAL.
 * ===========================================================================
 * Generated by scripts/generate-tests.mjs. Every item carries
 * `placeholder: true`. The figure matrices and number analogies are genuine
 * puzzles derived from docs/test-content/rule-taxonomy.md; the verbal analogies
 * are plainly filler. Difficulty is UNCALIBRATED for this grade.
 *
 * ===========================================================================
 * THE STRUCTURE, WHICH IS REAL
 * ===========================================================================
 * Fifteen items in five minutes, about twenty seconds each: 5 verbal analogies,
 * 5 number analogies, 5 figure matrices, interleaved.
 *
 * That is not an arbitrary truncation. The publisher of the instrument this
 * mirrors sells an official Screening Form that keeps ONLY the analogies
 * subtest from each of the three batteries — their own answer to "what is the
 * minimum viable version of this". Following that logic gives the short test a
 * rationale instead of a guess.
 *
 * NO LETTER SERIES: the child quantitative battery uses number series, not
 * letters. Paper folding is available to child tests but is not part of the
 * fifteen-item screening structure, so it belongs here only if this bank grows.
 *
 * TO LAND REAL CONTENT: edit this file. It is plain data, nothing regenerates
 * it at build time. Delete the `placeholder` flags as you go and run
 * `npm run verify:tests`.
 */
import type { Test } from "../types";

export const GRADE_6_TEST: Test = {
  id: "grade-6",
  audience: "child",
  bank: "grade-6",
  grades: [6],
  band: "grade-6",
  title: "The 5-Minute Grade 6 Test",
  durationSeconds: 5 * 60,
  allowBack: true,
  placeholder: true,
  items: [
    {
      id: "grade-6-01",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "B",
    },
    {
      id: "grade-6-02",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "4 is to 20 as 7 is to ?",
      options: [
        { id: "A", text: "28" },
        { id: "B", text: "42" },
        { id: "C", text: "35" },
        { id: "D", text: "23" },
      ],
      explanation: "The rule is multiply by 5, so 7 becomes 35.",
      answer: "C",
    },
    {
      id: "grade-6-03",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/containment+fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        {
          arrange: "stack",
          shapes: [{ shape: "arrow", size: "l" }, { shape: "triangle", size: "s" }],
        },
        {
          arrange: "stack",
          shapes: [
            { shape: "arrow", size: "l" },
            { shape: "triangle", size: "s", filled: true },
          ],
        },
        {
          arrange: "stack",
          shapes: [{ shape: "star", size: "l" }, { shape: "triangle", size: "s" }],
        },
      ],
      options: [
        {
          id: "A",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "star", size: "l" },
              { shape: "star", size: "s", filled: true },
            ],
          },
        },
        {
          id: "B",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "star", size: "l" },
              { shape: "triangle", size: "s", filled: true },
            ],
          },
        },
        {
          id: "C",
          fig: {
            arrange: "stack",
            shapes: [{ shape: "star", size: "l" }, { shape: "triangle", size: "s" }],
          },
        },
        {
          id: "D",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "arrow", size: "l" },
              { shape: "triangle", size: "s", filled: true },
            ],
          },
        },
      ],
      explanation: "The outer shape stays the same and the small shape inside it fills in.",
      answer: "B",
    },
    {
      id: "grade-6-04",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "A",
    },
    {
      id: "grade-6-05",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "3 is to 12 as 5 is to ?",
      options: [
        { id: "A", text: "14" },
        { id: "B", text: "15" },
        { id: "C", text: "25" },
        { id: "D", text: "20" },
      ],
      explanation: "The rule is multiply by 4, so 5 becomes 20.",
      answer: "D",
    },
    {
      id: "grade-6-06",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/containment+fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        {
          arrange: "stack",
          shapes: [{ shape: "triangle", size: "l" }, { shape: "heart", size: "s" }],
        },
        {
          arrange: "stack",
          shapes: [
            { shape: "triangle", size: "l" },
            { shape: "heart", size: "s", filled: true },
          ],
        },
        {
          arrange: "stack",
          shapes: [{ shape: "arrow", size: "l" }, { shape: "heart", size: "s" }],
        },
      ],
      options: [
        {
          id: "A",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "triangle", size: "l" },
              { shape: "heart", size: "s", filled: true },
            ],
          },
        },
        {
          id: "B",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "arrow", size: "l" },
              { shape: "arrow", size: "s", filled: true },
            ],
          },
        },
        {
          id: "C",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "arrow", size: "l" },
              { shape: "heart", size: "s", filled: true },
            ],
          },
        },
        {
          id: "D",
          fig: {
            arrange: "stack",
            shapes: [{ shape: "arrow", size: "l" }, { shape: "heart", size: "s" }],
          },
        },
      ],
      explanation: "The outer shape stays the same and the small shape inside it fills in.",
      answer: "C",
    },
    {
      id: "grade-6-07",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "D",
    },
    {
      id: "grade-6-08",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "2 is to 6 as 8 is to ?",
      options: [
        { id: "A", text: "24" },
        { id: "B", text: "12" },
        { id: "C", text: "16" },
        { id: "D", text: "32" },
      ],
      explanation: "The rule is multiply by 3, so 8 becomes 24.",
      answer: "A",
    },
    {
      id: "grade-6-09",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/containment+fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        {
          arrange: "stack",
          shapes: [{ shape: "heart", size: "l" }, { shape: "circle", size: "s" }],
        },
        {
          arrange: "stack",
          shapes: [
            { shape: "heart", size: "l" },
            { shape: "circle", size: "s", filled: true },
          ],
        },
        {
          arrange: "stack",
          shapes: [{ shape: "triangle", size: "l" }, { shape: "circle", size: "s" }],
        },
      ],
      options: [
        {
          id: "A",
          fig: {
            arrange: "stack",
            shapes: [{ shape: "triangle", size: "l" }, { shape: "circle", size: "s" }],
          },
        },
        {
          id: "B",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "heart", size: "l" },
              { shape: "circle", size: "s", filled: true },
            ],
          },
        },
        {
          id: "C",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "triangle", size: "l" },
              { shape: "triangle", size: "s", filled: true },
            ],
          },
        },
        {
          id: "D",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "triangle", size: "l" },
              { shape: "circle", size: "s", filled: true },
            ],
          },
        },
      ],
      explanation: "The outer shape stays the same and the small shape inside it fills in.",
      answer: "D",
    },
    {
      id: "grade-6-10",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "C",
    },
    {
      id: "grade-6-11",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "5 is to 30 as 6 is to ?",
      options: [
        { id: "A", text: "42" },
        { id: "B", text: "36" },
        { id: "C", text: "31" },
        { id: "D", text: "30" },
      ],
      explanation: "The rule is multiply by 6, so 6 becomes 36.",
      answer: "B",
    },
    {
      id: "grade-6-12",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/containment+fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        {
          arrange: "stack",
          shapes: [{ shape: "circle", size: "l" }, { shape: "diamond", size: "s" }],
        },
        {
          arrange: "stack",
          shapes: [
            { shape: "circle", size: "l" },
            { shape: "diamond", size: "s", filled: true },
          ],
        },
        {
          arrange: "stack",
          shapes: [{ shape: "heart", size: "l" }, { shape: "diamond", size: "s" }],
        },
      ],
      options: [
        {
          id: "A",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "heart", size: "l" },
              { shape: "diamond", size: "s", filled: true },
            ],
          },
        },
        {
          id: "B",
          fig: {
            arrange: "stack",
            shapes: [{ shape: "heart", size: "l" }, { shape: "diamond", size: "s" }],
          },
        },
        {
          id: "C",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "circle", size: "l" },
              { shape: "diamond", size: "s", filled: true },
            ],
          },
        },
        {
          id: "D",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "heart", size: "l" },
              { shape: "heart", size: "s", filled: true },
            ],
          },
        },
      ],
      explanation: "The outer shape stays the same and the small shape inside it fills in.",
      answer: "A",
    },
    {
      id: "grade-6-13",
      kind: "text",
      tier: "VERBAL ANALOGY",
      domain: "verbal",
      rule: "verbal/analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "PLACEHOLDER is to SAMPLE as FILLER is to ?",
      options: [
        { id: "A", text: "example" },
        { id: "B", text: "padding" },
        { id: "C", text: "draft" },
        { id: "D", text: "outline" },
      ],
      explanation: "Placeholder. Real content pending, generated from the rule taxonomy.",
      answer: "B",
    },
    {
      id: "grade-6-14",
      kind: "text",
      tier: "NUMBER ANALOGY",
      domain: "quantitative",
      rule: "quant/number-analogy",
      placeholder: true,
      prompt: "Complete the analogy.",
      stem: "4 is to 20 as 9 is to ?",
      options: [
        { id: "A", text: "36" },
        { id: "B", text: "54" },
        { id: "C", text: "45" },
        { id: "D", text: "25" },
      ],
      explanation: "The rule is multiply by 5, so 9 becomes 45.",
      answer: "C",
    },
    {
      id: "grade-6-15",
      kind: "figure",
      tier: "FIGURE MATRIX",
      domain: "spatial",
      rule: "figure/containment+fill",
      placeholder: true,
      prompt: "Which shape completes the grid?",
      layout: "matrix",
      cells: [
        {
          arrange: "stack",
          shapes: [{ shape: "diamond", size: "l" }, { shape: "cross", size: "s" }],
        },
        {
          arrange: "stack",
          shapes: [
            { shape: "diamond", size: "l" },
            { shape: "cross", size: "s", filled: true },
          ],
        },
        {
          arrange: "stack",
          shapes: [{ shape: "circle", size: "l" }, { shape: "cross", size: "s" }],
        },
      ],
      options: [
        {
          id: "A",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "circle", size: "l" },
              { shape: "circle", size: "s", filled: true },
            ],
          },
        },
        {
          id: "B",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "circle", size: "l" },
              { shape: "cross", size: "s", filled: true },
            ],
          },
        },
        {
          id: "C",
          fig: {
            arrange: "stack",
            shapes: [{ shape: "circle", size: "l" }, { shape: "cross", size: "s" }],
          },
        },
        {
          id: "D",
          fig: {
            arrange: "stack",
            shapes: [
              { shape: "diamond", size: "l" },
              { shape: "cross", size: "s", filled: true },
            ],
          },
        },
      ],
      explanation: "The outer shape stays the same and the small shape inside it fills in.",
      answer: "B",
    },
  ],
};
